### ISSUE TITLE
Impossible de lancer l'app sur unix 20.04.1-Ubuntu

### ISSUE THREAD

**Issue by janssens** [adaussy/permadeler#13]
erreur Java, peut-être il me manque une dépendance ou une mise à jour ?
![image](https://user-images.githubusercontent.com/675464/216281796-20a227a2-4c15-423a-a51e-cfe98aaaddaf.png)

**Comment by adaussy** [comment]
Bonjour,

Est-ce que tu as réussi à en sortir?

**Comment by adaussy** [comment]
Bonjour,

Pourrais tu me dire si tu as réussi à t'en sortir. Si oui je voudrais cloturer le bug

**Comment by janssens** [comment]
Salut Arthur,
Je ferais le point lundi mais non, je crois que j'avais abandonné et utilisé un boot windows

27 janv. 2024 18:19:58 Arthur Daussy ***@***.***>:

**Comment by janssens** [comment]
C''est ok, la dernière version se lance sans erreur sur ubuntu 22
